services:
  db:
    image: postgres:15
    container_name: chipnews_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chipnews
    ports:
      - "5432:5432"
